[tools]
node = "lts"
pnpm = "latest"
python = "3.13"
pre-commit = "latest"

[hooks]
enter = "bash ./scripts/enter_project.sh"

[env]
_.path = ['{{config_root}}/node_modules/.bin']

[settings]
experimental = true
lockfile = true

[tasks.dev]
description = "Dev Mode"
run = "astro dev --host 0.0.0.0"


[tasks.dicon]
description = "Downloads an SVG from svgrepo and saves it to src/assets/icons/"
run = "bash ./scripts/download-icon.sh"
